<?php


namespace app\modules\sellers\models;
use app\models\Model;
use app\models\Seller;


/**
 * Created by PhpStorm.
 * User: ganxi
 * Date: 2018-05-10
 * Time: 10:49
 */
class SellerForm extends Model{
    public $store_id;
    public $username;
    public $password;
    public $addtime;
    public $seller;
    public function rules()
    {
        return [
            [['password','username'],'required','on'=>'SUCCESS'],
            [['addtime','store_id'],'integer'],

        ];
    }

    public function attributeLabels()
    {
        return[
            'password'=>'密码',
            'username'=>'用户名'
            ]; // TODO: Change the autogenerated stub
    }


    public function login(){
        $seller=Seller::findOne(['username'=>$this->username,'password'=>md5($this->password)]);
        if($seller){
            \Yii::$app->session->set('seller_id',$seller->id);
            return true;
        }
        return false;
    }






}


