<?php
/**
 * Created by PhpStorm.
 * User: ganxi
 * Date: 2018-05-11
 * Time: 8:58
 */
namespace app\models;
/**
 * This is the model class for table "{{%guide_page}}".
 *
 * @property integer $id
 * @property string $appid
 * @property string $pic_url
 * @property integer $addtime
 */
class GuidePage extends Model{
   public static function tableName(){
       return '{{%guide_page}}';
   }


   public function rules()
   {
       return[
           [['appid','pic_url'],'required'],
           [['appid','pic_url'],'string'],
           [['addtime'],'integer'],
           [['pic_url'],'default','value'=>0]
       ];

   }

    public function attributeLabels()
    {
        return [
            'addid'=>'小程序的appid',
            'pic_url'=>'引导页图片的路径'

        ]; // TODO: Change the autogenerated stub
    }

}
